/*
 * This file is generated by jOOQ.
 */
package net.joostvdg.tektonvisualizer.model.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import net.joostvdg.tektonvisualizer.model.Keys;
import net.joostvdg.tektonvisualizer.model.Public;
import net.joostvdg.tektonvisualizer.model.tables.PipelineStatus.PipelineStatusPath;
import net.joostvdg.tektonvisualizer.model.tables.SupplyChain.SupplyChainPath;
import net.joostvdg.tektonvisualizer.model.tables.records.PipelineStatusSupplyChainRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PipelineStatusSupplyChain extends TableImpl<PipelineStatusSupplyChainRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.pipeline_status_supply_chain</code>
     */
    public static final PipelineStatusSupplyChain PIPELINE_STATUS_SUPPLY_CHAIN = new PipelineStatusSupplyChain();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PipelineStatusSupplyChainRecord> getRecordType() {
        return PipelineStatusSupplyChainRecord.class;
    }

    /**
     * The column
     * <code>public.pipeline_status_supply_chain.pipeline_status_id</code>.
     */
    public final TableField<PipelineStatusSupplyChainRecord, Integer> PIPELINE_STATUS_ID = createField(DSL.name("pipeline_status_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>public.pipeline_status_supply_chain.supply_chain_id</code>.
     */
    public final TableField<PipelineStatusSupplyChainRecord, Integer> SUPPLY_CHAIN_ID = createField(DSL.name("supply_chain_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private PipelineStatusSupplyChain(Name alias, Table<PipelineStatusSupplyChainRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PipelineStatusSupplyChain(Name alias, Table<PipelineStatusSupplyChainRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.pipeline_status_supply_chain</code> table
     * reference
     */
    public PipelineStatusSupplyChain(String alias) {
        this(DSL.name(alias), PIPELINE_STATUS_SUPPLY_CHAIN);
    }

    /**
     * Create an aliased <code>public.pipeline_status_supply_chain</code> table
     * reference
     */
    public PipelineStatusSupplyChain(Name alias) {
        this(alias, PIPELINE_STATUS_SUPPLY_CHAIN);
    }

    /**
     * Create a <code>public.pipeline_status_supply_chain</code> table reference
     */
    public PipelineStatusSupplyChain() {
        this(DSL.name("pipeline_status_supply_chain"), null);
    }

    public <O extends Record> PipelineStatusSupplyChain(Table<O> path, ForeignKey<O, PipelineStatusSupplyChainRecord> childPath, InverseForeignKey<O, PipelineStatusSupplyChainRecord> parentPath) {
        super(path, childPath, parentPath, PIPELINE_STATUS_SUPPLY_CHAIN);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PipelineStatusSupplyChainPath extends PipelineStatusSupplyChain implements Path<PipelineStatusSupplyChainRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PipelineStatusSupplyChainPath(Table<O> path, ForeignKey<O, PipelineStatusSupplyChainRecord> childPath, InverseForeignKey<O, PipelineStatusSupplyChainRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PipelineStatusSupplyChainPath(Name alias, Table<PipelineStatusSupplyChainRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PipelineStatusSupplyChainPath as(String alias) {
            return new PipelineStatusSupplyChainPath(DSL.name(alias), this);
        }

        @Override
        public PipelineStatusSupplyChainPath as(Name alias) {
            return new PipelineStatusSupplyChainPath(alias, this);
        }

        @Override
        public PipelineStatusSupplyChainPath as(Table<?> alias) {
            return new PipelineStatusSupplyChainPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PipelineStatusSupplyChainRecord> getPrimaryKey() {
        return Keys.PIPELINE_STATUS_SUPPLY_CHAIN_PKEY;
    }

    @Override
    public List<ForeignKey<PipelineStatusSupplyChainRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PIPELINE_STATUS_SUPPLY_CHAIN__PIPELINE_STATUS_SUPPLY_CHAIN_PIPELINE_STATUS_ID_FKEY, Keys.PIPELINE_STATUS_SUPPLY_CHAIN__PIPELINE_STATUS_SUPPLY_CHAIN_SUPPLY_CHAIN_ID_FKEY);
    }

    private transient PipelineStatusPath _pipelineStatus;

    /**
     * Get the implicit join path to the <code>public.pipeline_status</code>
     * table.
     */
    public PipelineStatusPath pipelineStatus() {
        if (_pipelineStatus == null)
            _pipelineStatus = new PipelineStatusPath(this, Keys.PIPELINE_STATUS_SUPPLY_CHAIN__PIPELINE_STATUS_SUPPLY_CHAIN_PIPELINE_STATUS_ID_FKEY, null);

        return _pipelineStatus;
    }

    private transient SupplyChainPath _supplyChain;

    /**
     * Get the implicit join path to the <code>public.supply_chain</code> table.
     */
    public SupplyChainPath supplyChain() {
        if (_supplyChain == null)
            _supplyChain = new SupplyChainPath(this, Keys.PIPELINE_STATUS_SUPPLY_CHAIN__PIPELINE_STATUS_SUPPLY_CHAIN_SUPPLY_CHAIN_ID_FKEY, null);

        return _supplyChain;
    }

    @Override
    public PipelineStatusSupplyChain as(String alias) {
        return new PipelineStatusSupplyChain(DSL.name(alias), this);
    }

    @Override
    public PipelineStatusSupplyChain as(Name alias) {
        return new PipelineStatusSupplyChain(alias, this);
    }

    @Override
    public PipelineStatusSupplyChain as(Table<?> alias) {
        return new PipelineStatusSupplyChain(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PipelineStatusSupplyChain rename(String name) {
        return new PipelineStatusSupplyChain(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PipelineStatusSupplyChain rename(Name name) {
        return new PipelineStatusSupplyChain(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PipelineStatusSupplyChain rename(Table<?> name) {
        return new PipelineStatusSupplyChain(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineStatusSupplyChain where(Condition condition) {
        return new PipelineStatusSupplyChain(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineStatusSupplyChain where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineStatusSupplyChain where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineStatusSupplyChain where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PipelineStatusSupplyChain where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PipelineStatusSupplyChain where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PipelineStatusSupplyChain where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PipelineStatusSupplyChain where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineStatusSupplyChain whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineStatusSupplyChain whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
