/*
 * This file is generated by jOOQ.
 */
package net.joostvdg.tektonvisualizer.model.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import net.joostvdg.tektonvisualizer.model.Keys;
import net.joostvdg.tektonvisualizer.model.Public;
import net.joostvdg.tektonvisualizer.model.tables.PipelineStatus.PipelineStatusPath;
import net.joostvdg.tektonvisualizer.model.tables.records.PipelineResultRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PipelineResult extends TableImpl<PipelineResultRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.pipeline_result</code>
     */
    public static final PipelineResult PIPELINE_RESULT = new PipelineResult();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PipelineResultRecord> getRecordType() {
        return PipelineResultRecord.class;
    }

    /**
     * The column <code>public.pipeline_result.id</code>.
     */
    public final TableField<PipelineResultRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.pipeline_result.pipeline_status_id</code>.
     */
    public final TableField<PipelineResultRecord, Integer> PIPELINE_STATUS_ID = createField(DSL.name("pipeline_status_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.pipeline_result.key</code>.
     */
    public final TableField<PipelineResultRecord, String> KEY = createField(DSL.name("key"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.pipeline_result.value</code>.
     */
    public final TableField<PipelineResultRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private PipelineResult(Name alias, Table<PipelineResultRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PipelineResult(Name alias, Table<PipelineResultRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.pipeline_result</code> table reference
     */
    public PipelineResult(String alias) {
        this(DSL.name(alias), PIPELINE_RESULT);
    }

    /**
     * Create an aliased <code>public.pipeline_result</code> table reference
     */
    public PipelineResult(Name alias) {
        this(alias, PIPELINE_RESULT);
    }

    /**
     * Create a <code>public.pipeline_result</code> table reference
     */
    public PipelineResult() {
        this(DSL.name("pipeline_result"), null);
    }

    public <O extends Record> PipelineResult(Table<O> path, ForeignKey<O, PipelineResultRecord> childPath, InverseForeignKey<O, PipelineResultRecord> parentPath) {
        super(path, childPath, parentPath, PIPELINE_RESULT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PipelineResultPath extends PipelineResult implements Path<PipelineResultRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PipelineResultPath(Table<O> path, ForeignKey<O, PipelineResultRecord> childPath, InverseForeignKey<O, PipelineResultRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PipelineResultPath(Name alias, Table<PipelineResultRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PipelineResultPath as(String alias) {
            return new PipelineResultPath(DSL.name(alias), this);
        }

        @Override
        public PipelineResultPath as(Name alias) {
            return new PipelineResultPath(alias, this);
        }

        @Override
        public PipelineResultPath as(Table<?> alias) {
            return new PipelineResultPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PipelineResultRecord, Integer> getIdentity() {
        return (Identity<PipelineResultRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PipelineResultRecord> getPrimaryKey() {
        return Keys.PIPELINE_RESULT_PKEY;
    }

    @Override
    public List<ForeignKey<PipelineResultRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PIPELINE_RESULT__PIPELINE_RESULT_PIPELINE_STATUS_ID_FKEY);
    }

    private transient PipelineStatusPath _pipelineStatus;

    /**
     * Get the implicit join path to the <code>public.pipeline_status</code>
     * table.
     */
    public PipelineStatusPath pipelineStatus() {
        if (_pipelineStatus == null)
            _pipelineStatus = new PipelineStatusPath(this, Keys.PIPELINE_RESULT__PIPELINE_RESULT_PIPELINE_STATUS_ID_FKEY, null);

        return _pipelineStatus;
    }

    @Override
    public PipelineResult as(String alias) {
        return new PipelineResult(DSL.name(alias), this);
    }

    @Override
    public PipelineResult as(Name alias) {
        return new PipelineResult(alias, this);
    }

    @Override
    public PipelineResult as(Table<?> alias) {
        return new PipelineResult(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PipelineResult rename(String name) {
        return new PipelineResult(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PipelineResult rename(Name name) {
        return new PipelineResult(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PipelineResult rename(Table<?> name) {
        return new PipelineResult(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineResult where(Condition condition) {
        return new PipelineResult(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineResult where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineResult where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineResult where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PipelineResult where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PipelineResult where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PipelineResult where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PipelineResult where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineResult whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineResult whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
