/*
 * This file is generated by jOOQ.
 */
package net.joostvdg.tektonvisualizer.model.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import net.joostvdg.tektonvisualizer.model.Keys;
import net.joostvdg.tektonvisualizer.model.Public;
import net.joostvdg.tektonvisualizer.model.tables.PipelineStatus.PipelineStatusPath;
import net.joostvdg.tektonvisualizer.model.tables.records.PipelineStageRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PipelineStage extends TableImpl<PipelineStageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.pipeline_stage</code>
     */
    public static final PipelineStage PIPELINE_STAGE = new PipelineStage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PipelineStageRecord> getRecordType() {
        return PipelineStageRecord.class;
    }

    /**
     * The column <code>public.pipeline_stage.id</code>.
     */
    public final TableField<PipelineStageRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.pipeline_stage.name</code>.
     */
    public final TableField<PipelineStageRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.pipeline_stage.pipeline_status_id</code>.
     */
    public final TableField<PipelineStageRecord, Integer> PIPELINE_STATUS_ID = createField(DSL.name("pipeline_status_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.pipeline_stage.duration</code>.
     */
    public final TableField<PipelineStageRecord, Integer> DURATION = createField(DSL.name("duration"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.pipeline_stage.order_number</code>.
     */
    public final TableField<PipelineStageRecord, Integer> ORDER_NUMBER = createField(DSL.name("order_number"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.pipeline_stage.success</code>.
     */
    public final TableField<PipelineStageRecord, Boolean> SUCCESS = createField(DSL.name("success"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.pipeline_stage.completion_message</code>.
     */
    public final TableField<PipelineStageRecord, String> COMPLETION_MESSAGE = createField(DSL.name("completion_message"), SQLDataType.VARCHAR(255), this, "");

    private PipelineStage(Name alias, Table<PipelineStageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PipelineStage(Name alias, Table<PipelineStageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.pipeline_stage</code> table reference
     */
    public PipelineStage(String alias) {
        this(DSL.name(alias), PIPELINE_STAGE);
    }

    /**
     * Create an aliased <code>public.pipeline_stage</code> table reference
     */
    public PipelineStage(Name alias) {
        this(alias, PIPELINE_STAGE);
    }

    /**
     * Create a <code>public.pipeline_stage</code> table reference
     */
    public PipelineStage() {
        this(DSL.name("pipeline_stage"), null);
    }

    public <O extends Record> PipelineStage(Table<O> path, ForeignKey<O, PipelineStageRecord> childPath, InverseForeignKey<O, PipelineStageRecord> parentPath) {
        super(path, childPath, parentPath, PIPELINE_STAGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PipelineStagePath extends PipelineStage implements Path<PipelineStageRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PipelineStagePath(Table<O> path, ForeignKey<O, PipelineStageRecord> childPath, InverseForeignKey<O, PipelineStageRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PipelineStagePath(Name alias, Table<PipelineStageRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PipelineStagePath as(String alias) {
            return new PipelineStagePath(DSL.name(alias), this);
        }

        @Override
        public PipelineStagePath as(Name alias) {
            return new PipelineStagePath(alias, this);
        }

        @Override
        public PipelineStagePath as(Table<?> alias) {
            return new PipelineStagePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PipelineStageRecord, Integer> getIdentity() {
        return (Identity<PipelineStageRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PipelineStageRecord> getPrimaryKey() {
        return Keys.PIPELINE_STAGE_PKEY;
    }

    @Override
    public List<ForeignKey<PipelineStageRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PIPELINE_STAGE__PIPELINE_STAGE_PIPELINE_STATUS_ID_FKEY);
    }

    private transient PipelineStatusPath _pipelineStatus;

    /**
     * Get the implicit join path to the <code>public.pipeline_status</code>
     * table.
     */
    public PipelineStatusPath pipelineStatus() {
        if (_pipelineStatus == null)
            _pipelineStatus = new PipelineStatusPath(this, Keys.PIPELINE_STAGE__PIPELINE_STAGE_PIPELINE_STATUS_ID_FKEY, null);

        return _pipelineStatus;
    }

    @Override
    public PipelineStage as(String alias) {
        return new PipelineStage(DSL.name(alias), this);
    }

    @Override
    public PipelineStage as(Name alias) {
        return new PipelineStage(alias, this);
    }

    @Override
    public PipelineStage as(Table<?> alias) {
        return new PipelineStage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PipelineStage rename(String name) {
        return new PipelineStage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PipelineStage rename(Name name) {
        return new PipelineStage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PipelineStage rename(Table<?> name) {
        return new PipelineStage(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineStage where(Condition condition) {
        return new PipelineStage(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineStage where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineStage where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineStage where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PipelineStage where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PipelineStage where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PipelineStage where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PipelineStage where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineStage whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PipelineStage whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
