/*
 * This file is generated by jOOQ.
 */
package net.joostvdg.tektonvisualizer.model;


import java.util.Arrays;
import java.util.List;

import net.joostvdg.tektonvisualizer.model.tables.CodeSource;
import net.joostvdg.tektonvisualizer.model.tables.FlywaySchemaHistory;
import net.joostvdg.tektonvisualizer.model.tables.PipelineResult;
import net.joostvdg.tektonvisualizer.model.tables.PipelineStage;
import net.joostvdg.tektonvisualizer.model.tables.PipelineStatus;
import net.joostvdg.tektonvisualizer.model.tables.PipelineStatusSupplyChain;
import net.joostvdg.tektonvisualizer.model.tables.PipelineTrigger;
import net.joostvdg.tektonvisualizer.model.tables.SupplyChain;
import net.joostvdg.tektonvisualizer.model.tables.SupplyChainCodeSource;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.code_source</code>.
     */
    public final CodeSource CODE_SOURCE = CodeSource.CODE_SOURCE;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.pipeline_result</code>.
     */
    public final PipelineResult PIPELINE_RESULT = PipelineResult.PIPELINE_RESULT;

    /**
     * The table <code>public.pipeline_stage</code>.
     */
    public final PipelineStage PIPELINE_STAGE = PipelineStage.PIPELINE_STAGE;

    /**
     * The table <code>public.pipeline_status</code>.
     */
    public final PipelineStatus PIPELINE_STATUS = PipelineStatus.PIPELINE_STATUS;

    /**
     * The table <code>public.pipeline_status_supply_chain</code>.
     */
    public final PipelineStatusSupplyChain PIPELINE_STATUS_SUPPLY_CHAIN = PipelineStatusSupplyChain.PIPELINE_STATUS_SUPPLY_CHAIN;

    /**
     * The table <code>public.pipeline_trigger</code>.
     */
    public final PipelineTrigger PIPELINE_TRIGGER = PipelineTrigger.PIPELINE_TRIGGER;

    /**
     * The table <code>public.supply_chain</code>.
     */
    public final SupplyChain SUPPLY_CHAIN = SupplyChain.SUPPLY_CHAIN;

    /**
     * The table <code>public.supply_chain_code_source</code>.
     */
    public final SupplyChainCodeSource SUPPLY_CHAIN_CODE_SOURCE = SupplyChainCodeSource.SUPPLY_CHAIN_CODE_SOURCE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CodeSource.CODE_SOURCE,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            PipelineResult.PIPELINE_RESULT,
            PipelineStage.PIPELINE_STAGE,
            PipelineStatus.PIPELINE_STATUS,
            PipelineStatusSupplyChain.PIPELINE_STATUS_SUPPLY_CHAIN,
            PipelineTrigger.PIPELINE_TRIGGER,
            SupplyChain.SUPPLY_CHAIN,
            SupplyChainCodeSource.SUPPLY_CHAIN_CODE_SOURCE
        );
    }
}
