/*
 * This file is generated by jOOQ.
 */
package net.joostvdg.tektonvisualizer.model;


import net.joostvdg.tektonvisualizer.model.tables.CodeSource;
import net.joostvdg.tektonvisualizer.model.tables.FlywaySchemaHistory;
import net.joostvdg.tektonvisualizer.model.tables.PipelineResult;
import net.joostvdg.tektonvisualizer.model.tables.PipelineStage;
import net.joostvdg.tektonvisualizer.model.tables.PipelineStatus;
import net.joostvdg.tektonvisualizer.model.tables.PipelineStatusSupplyChain;
import net.joostvdg.tektonvisualizer.model.tables.PipelineTrigger;
import net.joostvdg.tektonvisualizer.model.tables.SupplyChain;
import net.joostvdg.tektonvisualizer.model.tables.SupplyChainCodeSource;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.code_source</code>.
     */
    public static final CodeSource CODE_SOURCE = CodeSource.CODE_SOURCE;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.pipeline_result</code>.
     */
    public static final PipelineResult PIPELINE_RESULT = PipelineResult.PIPELINE_RESULT;

    /**
     * The table <code>public.pipeline_stage</code>.
     */
    public static final PipelineStage PIPELINE_STAGE = PipelineStage.PIPELINE_STAGE;

    /**
     * The table <code>public.pipeline_status</code>.
     */
    public static final PipelineStatus PIPELINE_STATUS = PipelineStatus.PIPELINE_STATUS;

    /**
     * The table <code>public.pipeline_status_supply_chain</code>.
     */
    public static final PipelineStatusSupplyChain PIPELINE_STATUS_SUPPLY_CHAIN = PipelineStatusSupplyChain.PIPELINE_STATUS_SUPPLY_CHAIN;

    /**
     * The table <code>public.pipeline_trigger</code>.
     */
    public static final PipelineTrigger PIPELINE_TRIGGER = PipelineTrigger.PIPELINE_TRIGGER;

    /**
     * The table <code>public.supply_chain</code>.
     */
    public static final SupplyChain SUPPLY_CHAIN = SupplyChain.SUPPLY_CHAIN;

    /**
     * The table <code>public.supply_chain_code_source</code>.
     */
    public static final SupplyChainCodeSource SUPPLY_CHAIN_CODE_SOURCE = SupplyChainCodeSource.SUPPLY_CHAIN_CODE_SOURCE;
}
