/*
 * This file is generated by jOOQ.
 */
package net.joostvdg.tektonvisualizer.model.tables.records;


import net.joostvdg.tektonvisualizer.model.tables.PipelineStatusSupplyChain;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PipelineStatusSupplyChainRecord extends UpdatableRecordImpl<PipelineStatusSupplyChainRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.pipeline_status_supply_chain.pipeline_status_id</code>.
     */
    public void setPipelineStatusId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.pipeline_status_supply_chain.pipeline_status_id</code>.
     */
    public Integer getPipelineStatusId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>public.pipeline_status_supply_chain.supply_chain_id</code>.
     */
    public void setSupplyChainId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.pipeline_status_supply_chain.supply_chain_id</code>.
     */
    public Integer getSupplyChainId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PipelineStatusSupplyChainRecord
     */
    public PipelineStatusSupplyChainRecord() {
        super(PipelineStatusSupplyChain.PIPELINE_STATUS_SUPPLY_CHAIN);
    }

    /**
     * Create a detached, initialised PipelineStatusSupplyChainRecord
     */
    public PipelineStatusSupplyChainRecord(Integer pipelineStatusId, Integer supplyChainId) {
        super(PipelineStatusSupplyChain.PIPELINE_STATUS_SUPPLY_CHAIN);

        setPipelineStatusId(pipelineStatusId);
        setSupplyChainId(supplyChainId);
        resetChangedOnNotNull();
    }
}
