/*
 * This file is generated by jOOQ.
 */
package net.joostvdg.tektonvisualizer.model.tables.records;


import java.time.OffsetDateTime;

import net.joostvdg.tektonvisualizer.model.tables.PipelineStatus;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PipelineStatusRecord extends UpdatableRecordImpl<PipelineStatusRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.pipeline_status.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pipeline_status.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.pipeline_status.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pipeline_status.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.pipeline_status.pipeline_id</code>.
     */
    public void setPipelineId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pipeline_status.pipeline_id</code>.
     */
    public String getPipelineId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.pipeline_status.start_timestamp</code>.
     */
    public void setStartTimestamp(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.pipeline_status.start_timestamp</code>.
     */
    public OffsetDateTime getStartTimestamp() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.pipeline_status.duration</code>.
     */
    public void setDuration(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.pipeline_status.duration</code>.
     */
    public Long getDuration() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.pipeline_status.success</code>.
     */
    public void setSuccess(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.pipeline_status.success</code>.
     */
    public Boolean getSuccess() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.pipeline_status.completion_message</code>.
     */
    public void setCompletionMessage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.pipeline_status.completion_message</code>.
     */
    public String getCompletionMessage() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PipelineStatusRecord
     */
    public PipelineStatusRecord() {
        super(PipelineStatus.PIPELINE_STATUS);
    }

    /**
     * Create a detached, initialised PipelineStatusRecord
     */
    public PipelineStatusRecord(Integer id, String name, String pipelineId, OffsetDateTime startTimestamp, Long duration, Boolean success, String completionMessage) {
        super(PipelineStatus.PIPELINE_STATUS);

        setId(id);
        setName(name);
        setPipelineId(pipelineId);
        setStartTimestamp(startTimestamp);
        setDuration(duration);
        setSuccess(success);
        setCompletionMessage(completionMessage);
        resetChangedOnNotNull();
    }
}
