/*
 * This file is generated by jOOQ.
 */
package net.joostvdg.tektonvisualizer.model.tables.records;


import net.joostvdg.tektonvisualizer.model.tables.PipelineStage;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PipelineStageRecord extends UpdatableRecordImpl<PipelineStageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.pipeline_stage.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pipeline_stage.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.pipeline_stage.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pipeline_stage.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.pipeline_stage.pipeline_status_id</code>.
     */
    public void setPipelineStatusId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pipeline_stage.pipeline_status_id</code>.
     */
    public Integer getPipelineStatusId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.pipeline_stage.duration</code>.
     */
    public void setDuration(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.pipeline_stage.duration</code>.
     */
    public Integer getDuration() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.pipeline_stage.order_number</code>.
     */
    public void setOrderNumber(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.pipeline_stage.order_number</code>.
     */
    public Integer getOrderNumber() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.pipeline_stage.success</code>.
     */
    public void setSuccess(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.pipeline_stage.success</code>.
     */
    public Boolean getSuccess() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.pipeline_stage.completion_message</code>.
     */
    public void setCompletionMessage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.pipeline_stage.completion_message</code>.
     */
    public String getCompletionMessage() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PipelineStageRecord
     */
    public PipelineStageRecord() {
        super(PipelineStage.PIPELINE_STAGE);
    }

    /**
     * Create a detached, initialised PipelineStageRecord
     */
    public PipelineStageRecord(Integer id, String name, Integer pipelineStatusId, Integer duration, Integer orderNumber, Boolean success, String completionMessage) {
        super(PipelineStage.PIPELINE_STAGE);

        setId(id);
        setName(name);
        setPipelineStatusId(pipelineStatusId);
        setDuration(duration);
        setOrderNumber(orderNumber);
        setSuccess(success);
        setCompletionMessage(completionMessage);
        resetChangedOnNotNull();
    }
}
