/*
 * This file is generated by jOOQ.
 */
package net.joostvdg.tektonvisualizer.model.tables.records;


import net.joostvdg.tektonvisualizer.model.tables.PipelineResult;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PipelineResultRecord extends UpdatableRecordImpl<PipelineResultRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.pipeline_result.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pipeline_result.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.pipeline_result.pipeline_status_id</code>.
     */
    public void setPipelineStatusId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pipeline_result.pipeline_status_id</code>.
     */
    public Integer getPipelineStatusId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.pipeline_result.key</code>.
     */
    public void setKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pipeline_result.key</code>.
     */
    public String getKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.pipeline_result.value</code>.
     */
    public void setValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.pipeline_result.value</code>.
     */
    public String getValue() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PipelineResultRecord
     */
    public PipelineResultRecord() {
        super(PipelineResult.PIPELINE_RESULT);
    }

    /**
     * Create a detached, initialised PipelineResultRecord
     */
    public PipelineResultRecord(Integer id, Integer pipelineStatusId, String key, String value) {
        super(PipelineResult.PIPELINE_RESULT);

        setId(id);
        setPipelineStatusId(pipelineStatusId);
        setKey(key);
        setValue(value);
        resetChangedOnNotNull();
    }
}
