/*
 * This file is generated by jOOQ.
 */
package net.joostvdg.tektonvisualizer.model.tables.records;


import net.joostvdg.tektonvisualizer.model.tables.SupplyChainCodeSource;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SupplyChainCodeSourceRecord extends UpdatableRecordImpl<SupplyChainCodeSourceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.supply_chain_code_source.supply_chain_id</code>.
     */
    public void setSupplyChainId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.supply_chain_code_source.supply_chain_id</code>.
     */
    public Integer getSupplyChainId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.supply_chain_code_source.code_source_id</code>.
     */
    public void setCodeSourceId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.supply_chain_code_source.code_source_id</code>.
     */
    public Integer getCodeSourceId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SupplyChainCodeSourceRecord
     */
    public SupplyChainCodeSourceRecord() {
        super(SupplyChainCodeSource.SUPPLY_CHAIN_CODE_SOURCE);
    }

    /**
     * Create a detached, initialised SupplyChainCodeSourceRecord
     */
    public SupplyChainCodeSourceRecord(Integer supplyChainId, Integer codeSourceId) {
        super(SupplyChainCodeSource.SUPPLY_CHAIN_CODE_SOURCE);

        setSupplyChainId(supplyChainId);
        setCodeSourceId(codeSourceId);
        resetChangedOnNotNull();
    }
}
