/*
 * This file is generated by jOOQ.
 */
package net.joostvdg.tektonvisualizer.model.tables.records;


import net.joostvdg.tektonvisualizer.model.tables.SupplyChain;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SupplyChainRecord extends UpdatableRecordImpl<SupplyChainRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.supply_chain.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.supply_chain.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.supply_chain.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.supply_chain.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SupplyChainRecord
     */
    public SupplyChainRecord() {
        super(SupplyChain.SUPPLY_CHAIN);
    }

    /**
     * Create a detached, initialised SupplyChainRecord
     */
    public SupplyChainRecord(Integer id, String name) {
        super(SupplyChain.SUPPLY_CHAIN);

        setId(id);
        setName(name);
        resetChangedOnNotNull();
    }
}
