/* (C)2024 */
package net.joostvdg.tektonvisualizer.model;

import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.Objects;

/**
 * Represents the status of a Tekton Pipeline, capturing the results, stages, status, start and end
 * time and duration.
 *
 * @param pipelineIdentifier The identifier of the pipeline to associate this status with
 * @param results Any results generated by the pipeline
 * @param stages The stages of the pipeline
 * @param status The status of the pipeline
 * @param endInstant The point in time the pipeline ended
 * @param startIntant The point in time the pipeline started
 * @return PipelineStatus Returns a PipelineStatus object <br>
 *     <p>Example:
 *     <pre>{@code
 * PipelineStatus pipelineStatus = new PipelineStatus.Builder()
 *     .identifier("id")
 *     .pipelineIdentifier("pipelineId")
 *     .results(results)
 *     .stages(stages)
 *     .status(ExecutionStatus.SUCCEEDED)
 *     .endInstant(endInstant)
 *     .startIntant(startIntant)
 *     .duration(Duration.ofHours(1))
 *     .build();
 * }</pre>
 */
public record PipelineStatus(
    String identifier,
    String pipelineIdentifier,
    List<Result> results,
    List<PipelineStage> stages,
    ExecutionStatus status,
    Instant endInstant,
    Instant startIntant,
    Duration duration) {
  public PipelineStatus {
    Objects.requireNonNull(pipelineIdentifier, "PipelineIdentifier cannot be null");
    Objects.requireNonNull(results, "Results cannot be null");
    Objects.requireNonNull(stages, "Stages cannot be null");
    Objects.requireNonNull(status, "Status cannot be null");
    Objects.requireNonNull(endInstant, "EndInstance cannot be null");
    Objects.requireNonNull(startIntant, "StartInstance cannot be null");
    // Calculate duration if not provided
    if (duration == null) {
      duration = Duration.between(startIntant, endInstant);
    }
    // Generate GUID if the Identifier is not provided
    if (identifier == null || identifier.isBlank()) {
      identifier = java.util.UUID.randomUUID().toString();
    }
  }

  public static class Builder {
    private String identifier;
    private String pipelineIdentifier;
    private List<Result> results;
    private List<PipelineStage> stages;
    private ExecutionStatus status;
    private Instant endInstance;
    private Instant startInstance;
    private Duration duration;

    public Builder identifier(String identifier) {
      this.identifier = identifier;
      return this;
    }

    public Builder pipelineIdentifier(String pipelineIdentifier) {
      this.pipelineIdentifier = pipelineIdentifier;
      return this;
    }

    public Builder results(List<Result> results) {
      this.results = results;
      return this;
    }

    public Builder stages(List<PipelineStage> stages) {
      this.stages = stages;
      return this;
    }

    public Builder status(ExecutionStatus status) {
      this.status = status;
      return this;
    }

    public Builder endInstance(Instant endInstance) {
      this.endInstance = endInstance;
      return this;
    }

    public Builder startInstance(Instant startInstance) {
      this.startInstance = startInstance;
      return this;
    }

    public Builder duration(Duration duration) {
      this.duration = duration;
      return this;
    }

    public PipelineStatus build() {
      return new PipelineStatus(
          identifier,
          pipelineIdentifier,
          results,
          stages,
          status,
          endInstance,
          startInstance,
          duration);
    }
  }
}
