spring:
  threads:
    virtual:
      enabled: true
  application:
    name: Harvester

management:
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: "health,info"
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

  endpoint:
    info:
      enabled: true
    health:
      probes:
        enabled: true
        add-additional-paths=true:
          enabled: true
          additional-paths: "/liveness, /readiness"